public enum AchievementNames
{
SUPER_ONE_GAME,
MIDDLE_ONE_GAME,
FAIL_ONE_GAME,
PLAY_ALL_GAMES,
PLAY_ONE_GAME,
SUPER_THREE,
MIDDLE_THREE,
FAIL_THREE,
PLAY_EPI_ONE,
PLAY_EPI_TWO,
PLAY_EPI_THREE,
PLAY_EPI_FOUR,
PLAY_EPI_FIVE,
}